### ISSUE TITLE
[P-03] Commit-reveal peg operations

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#230]
## Definition of Done
sBTC burnchain operations support a format usable from custodian wallets.

```[tasklist]
### Milestones
- [ ] https://github.com/Trust-Machines/core-eng/issues/236
- [ ] https://github.com/Trust-Machines/core-eng/issues/271
- [ ] https://github.com/Trust-Machines/core-eng/issues/280
- [ ] https://github.com/Trust-Machines/core-eng/issues/281
- [ ] #151
- [ ] https://github.com/Trust-Machines/core-eng/issues/413
- [ ] Implement a standalone reference Revealer
- [ ] Implement a reference Committer
- [ ] Integration test for commit-reveal flow
- [ ] Integrate commit-reveal operations in sBTC
```

**Comment by igorsyl** [comment]
Perhaps we should rename this project to "Escrow system" to highlight the problem/purpose rather solution/implementation.

**Comment by netrome** [comment]
> Perhaps we should rename this project to "Escrow system" to highlight the problem/purpose rather solution/implementation.

I see I didn't reply to this.  The escrow-related properties of the system is a nice side-effect of the design, but when it comes to naming I think "commit-reveal operations" better encompass what we are building.

**Comment by netrome** [comment]
Closing this issue in favor of the sBTC SDK and documentation work being tracked in the Stacks Core Eng project.
