### ISSUE TITLE
[P-02] Peg-handoff system

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#231]
## Definition of done
We have a secure mechanism to hand over custody of the sBTC peg wallet.

```[tasklist]
### Milestones
- [ ] https://github.com/Trust-Machines/core-eng/issues/270
- [ ] https://github.com/Trust-Machines/core-eng/issues/302
- [ ] https://github.com/Trust-Machines/core-eng/issues/161
```

**Comment by netrome** [comment]
This week: Nothing, it's dependent on P-03

**Comment by netrome** [comment]
Closing this issue in favor of the new Stacks Core Eng board and project structure.
