### ISSUE TITLE
[P-24] Alpha coordinator

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#235]
## Definition of done
Stacks signers can coordinate to fulfill their responsibilities as needed for sBTC alpha.

```[tasklist]
### Milestones
- [ ] https://github.com/Trust-Machines/core-eng/issues/247
- [ ] https://github.com/Trust-Machines/core-eng/issues/213
- [ ] https://github.com/Trust-Machines/core-eng/issues/248
- [ ] https://github.com/Trust-Machines/core-eng/issues/216
- [ ] https://github.com/Trust-Machines/core-eng/issues/263
- [ ] https://github.com/Trust-Machines/core-eng/issues/262
- [ ] https://github.com/Trust-Machines/core-eng/issues/325
- [ ] https://github.com/Trust-Machines/core-eng/issues/327
- [ ] https://github.com/Trust-Machines/core-eng/issues/16
- [ ] https://github.com/Trust-Machines/core-eng/issues/37
```

**Comment by netrome** [comment]
This week:

- sBTC contract calls from coordinator (currently experiencing verification problems).
