### ISSUE TITLE
Clarity WG: Bugs & Minor Improvements for July "Barebones"

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#515]
```[tasklist]
### Tasks
- [ ] https://github.com/Trust-Machines/stacks-sbtc/pull/51
- [ ] https://github.com/Trust-Machines/stacks-sbtc/pull/512
- [ ] https://github.com/Trust-Machines/stacks-sbtc/pull/511
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/490
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/436
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/491
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/493
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/494
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/500
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/507
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/519
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/549
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/616
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/547
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/548
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/562
```

**Comment by jo-tm** [comment]
Closing issue at the end of July, pending issue moved to Sprint 2 tasklist, probably Sprint 2 tasklist will include all isues, major and minor.
