### ISSUE TITLE
Clarity WG - sBTC Mini 2 August "Most Functionality"

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#524]
```[tasklist]
### Tasks
- [ ] https://github.com/Trust-Machines/core-eng/issues/464
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/525
- [ ] https://github.com/Trust-Machines/stacks-sbtc/issues/517
```

**Comment by jo-tm** [comment]
Closing because we are moving to 2-week Sprint approach, the deadline of end of September is maintained.
